#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PropExample.Resource", IsApplication=true)]

namespace PropExample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int btnAddIm = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int btnAddP = 2131099663;
			
			// aapt resource value: 0x7f06001a
			public const int btnRegister = 2131099674;
			
			// aapt resource value: 0x7f060001
			public const int button1 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int button2 = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int editAddress = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int editBath = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int editBed = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int editCit = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int editDesc = 2131099654;
			
			// aapt resource value: 0x7f060018
			public const int editEmail = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int editFirst = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int editLast = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int editPass = 2131099673;
			
			// aapt resource value: 0x7f06000e
			public const int editPrice = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int editStat = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int editText1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int editText2 = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int editType = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int editgar = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060014
			public const int inputSearch = 2131099668;
			
			// aapt resource value: 0x7f06001c
			public const int item1 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int item2 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int item3 = 2131099678;
			
			// aapt resource value: 0x7f060015
			public const int listProperty = 2131099669;
			
			// aapt resource value: 0x7f060005
			public const int textAddp = 2131099653;
			
			// aapt resource value: 0x7f06001b
			public const int textView1 = 2131099675;
			
			// aapt resource value: 0x7f060013
			public const int txtCreate = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int txtDesc = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int txtType = 2131099666;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddImage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddProperty = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListDesign = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Register = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int PropMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040016
			public const int AddImage = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int AddProp = 2130968599;
			
			// aapt resource value: 0x7f040010
			public const int Adress = 2130968592;
			
			// aapt resource value: 0x7f040008
			public const int Already = 2130968584;
			
			// aapt resource value: 0x7f040013
			public const int Bath = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int Bed = 2130968594;
			
			// aapt resource value: 0x7f04000b
			public const int ChooseImg = 2130968587;
			
			// aapt resource value: 0x7f040011
			public const int City = 2130968593;
			
			// aapt resource value: 0x7f040007
			public const int Create = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int Email = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int First = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int ImgName = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int Last = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int Login = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int Pass = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int Price = 2130968597;
			
			// aapt resource value: 0x7f04000d
			public const int PropDesc = 2130968589;
			
			// aapt resource value: 0x7f04000a
			public const int PropID = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int PropStat = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int PropType = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int SendImgDb = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040014
			public const int garage = 2130968596;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
